### ISSUE TITLE
Timetable synchronization doesn't refresh the currently displayed day

### ISSUE THREAD

**Issue by TheChilliPL** [szkolny-eu/szkolny-android#125] opened 2022-01-20 04:00 UTC
Steps to reproduce:
1. Open the Timetable
2. Select one of the days that aren't synchronized yet
3. Press the Synchronize button

Expected outcome:
The timetable should synchronize and display the selected day.

Actual outcome:
After the synchronization, every day of the synchronized week is visible except for the day that was visible before you synchronized—it gets stuck on the No timetable screen with the Synchronize button grayed out.

![image](https://user-images.githubusercontent.com/18823939/150270536-6b405510-e009-4705-8c4c-d665dd1c4152.png)

Switching to another tab like Home or Grades after the synchronization and switching back to Timetable seems to refresh the day and show it properly.

Occurring on:
1. Oppo AX7 CPH 1903, Android 8.1.0
2. Windows Subsystem for Android

In both cases Szkolny.eu 4.11.1, version from the webpage, using for Librus with e-mail login.

**Comment by Antoni-Czaplicki** [comment] 2022-02-07 07:28
Duplicate of #90

**Comment by kuba2k2** [comment] 2022-02-21 20:07
Thanks! Will be fixed in v4.11.3.

**Closed** 2022-02-21 20:49 UTC
Labels: bug
